version: '3'
services:
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - postgres
    php:
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./src:/var/www/html

    postgres:
        container_name: postgres_container
        image: postgres
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./.docker/conf/postgres:/var/lib/postgresql/data
        ports:
            - ${DB_PORT}:5432
        restart: unless-stopped
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080